name: End to End CI/CD workflow for Java Applicaton with Maven, Sonar and k8s Intergation
#comment1
on:
  push:
    branches:
      - main

env:
  KUBECONFIG: ${{ secrets.KUBECONFIG }}
  SONAR_TOKEN: ${{ secrets.SONAR_TKN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Java jdk setup
      uses: actions/setup-java@v1
      with:
        java-version: 12

    - name: maven target # change accordingly
      run: mvn clean install

    - name: Perform analysis on Sonar Qube
      uses: sonarsource/sonarcloud-github-action@v1
